### ISSUE TITLE
Clean up the code

### ISSUE THREAD

**Issue by pbaisla** [Worm4047/MP3_down#4]
- [x] `re` and `urllib` modules are imported but never used
- [x] Use consistent indentation
- [x] `proxy_dict` and `*_proxy` variables are also unused and should be removed
- [x] Make code reusable by putting all the code outside functions into a `if __name__ == '__main__'` block
- [x] Make sure code adheres to [PEP8](https://www.python.org/dev/peps/pep-0008/)

**Comment by Worm4047** [comment]
Thanks for your feedback and i hope issues have been fixed .

**Comment by pbaisla** [comment]
Indentation is still a bit off [here](https://github.com/Worm4047/MP3_down/blob/master/mp3_down.py#L52,L56) and there's extra whitespace in places. Other than that it looks good :+1: 

I think fixing #1 should be your first priority though. #3 appears to be the same problem.
